#!/bin/bash

#force the script to run from this directory if double click
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"

dirName="build/"

# if the build directory does not already exist, then create it.
if [ ! -d $dirName ]
then
    mkdir $dirName
    echo "Created $dirName directory."
else
    echo "Directory already exists."
fi

cd $dirName
pwd
cmake -G Xcode ..

if [ "$1" == "-e" ]; then
    echo "building externals..."
    cmake --build .
fi
    
